# Generated by Django 5.1.3 on 2024-11-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('model_type', models.CharField(max_length=20)),
                ('mse', models.FloatField(blank=True, null=True)),
                ('mae', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
